name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Sender and Receiver Images
        run: |
          docker build -t emanueladler/can-sender:${{ github.ref_name }} -f sender/Dockerfile .
          docker build -t emanueladler/can-receiver:${{ github.ref_name }} -f receiver/Dockerfile .

      - name: Push Images to Docker Hub
        run: |
          docker push emanueladler/can-sender:${{ github.ref_name }}
          docker push emanueladler/can-receiver:${{ github.ref_name }}

      - name: Test Docker Compose
        run: |
          docker-compose up -d
          sleep 20
          docker ps
          docker-compose down

